import sys
import math
import random
# Auto-generated code below aims at helping you parse
# the standard input according to the problem statement.

def dist(a,b):
    return (a[0]-b[0])**2 + (a[1]-b[1])**2

# P: number of players in the game (2 to 4 players)
# ID: ID of your player (0, 1, 2, or 3)
# D: number of drones in each team (3 to 11)
# Z: number of zones on the map (4 to 8)

wd = 4000
ht = 1800

P, ID, D, Z = [int(i) for i in input().split()]

Zs = []
for i in range(Z):
        # X: corresponds to the position of the center of a zone. A zone is a circle with a radius of 100 units.
            Zs.append([int(i) for i in input().split()])

# game loop
Ds = [[] for x in range(P)]

TIDs = [int(input()) for i in range(Z)]  # ID of the team controlling the zone (0, 1, 2, or 3) or -1 if it is not controlled. The zones are given in the same order as in the initialization.
for i in range(P):
        for j in range(D):
                    # DX: The first D lines contain the coordinates of drones of a player with the ID 0, the following D lines those of the drones of player 1, and thus it continues until the last player.
                            Ds[i].append([int(i) for i in input().split()])
                            for j in range(D):
                                    print(random.randint(0,wd), random.randint(0,ht))

#game loop
while 1:
        _Ds = Ds
            Ds = [[] for x in range(P)]
                TIDs = [int(input()) for i in range(Z)] #zone controllers
                    for i in range(P):
                                for j in range(D):
                                                # DX: The first D lines contain the coordinates of drones of a player with the ID 0, the following D lines those of the drones of player 1, and thus it continues until the last player.
                                                            Ds[i].append([int(i) for i in input().split()])
                                                                       
                                                                           maxDpZ = []
                                                                               for x, y in Zs:
                                                                                           maxDpZ.append(0)
                                                                                                   for i in range(P):
                                                                                                                   if i == ID:
                                                                                                                                       continue
                                                                                                                                                   foo = 0
                                                                                                                                                               for j in range(D):
                                                                                                                                                                                   dx = Ds[i][j][0] 
                                                                                                                                                                                                   dy = Ds[i][j][1] 
                                                                                                                                                                                                                   _dx = Ds[i][j][0] 
                                                                                                                                                                                                                                   _dy = _Ds[i][j][1] 

                                                                                                                                                                                                                                                   dotp1 = (dx-_dx)*(x-_dx) +  (dy-_dy)*(y-_dy) 
                                                                                                                                                                                                                                                                   norm =  math.sqrt((dx-_dx)**2 + (dy-_dy)**2)
                                                                                                                                                                                                                                                                                   norm *= math.sqrt((x-_dx)**2 + (y-_dy)**2)
                                                                                                                                                                                                                                                                                                   if dotp1 <norm*0.98 or (x-dx)**2 + (y-dy) **2 < 10000:
                                                                                                                                                                                                                                                                                                                           foo +=1
                                                                                                                                                                                                                                                                                                                                       if foo >maxDpZ[-1]:
                                                                                                                                                                                                                                                                                                                                                           maxDpZ[-1] = foo

                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                               #sort the coordinates of zones by n o enemies.


                                                                                                                                                                                                                                                                                                                                                                                   Zones = [x for x in zip(maxDpZ, range(Z))]
                                                                                                                                                                                                                                                                                                                                                                                       Zones.sort(key = lambda k: k[0], reverse=False)
                                                                                                                                                                                                                                                                                                                                                                                           print(Zones, file=sys.stderr)

                                                                                                                                                                                                                                                                                                                                                                                               dest = [None for x in range(D)]
                                                                                                                                                                                                                                                                                                                                                                                                   moving = [False for x in range(D)]
                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                           dset = list(range(D))
                                                                                                                                                                                                                                                                                                                                                                                                              #problem is that the order of the zones 
                                                                                                                                                                                                                                                                                                                                                                                                                 #changes and the order of the drones if they are tied.
                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                         for i in range(Z):
                                                                                                                                                                                                                                                                                                                                                                                                                                 #temporary list of closest drones.
                                                                                                                                                                                                                                                                                                                                                                                                                                         drones = [(dist(Zones[i][1], Ds[ID][x]), x) for x in range(D)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                 drones.sort(key = lambda b: b[0]+b[1], reverse=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                         foo = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 for x in range(D):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if foo > Zones[i][0]: break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 #take the id of the closest drones. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #set ther destination if not set before
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         #if we have placed enough drones
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if not moving[drones[x][1]]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         dest[drones[x][1]] = Zones[i][1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         moving[drones[x][1]] = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         foo +=1                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 for i in range(D):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             # Write an action using print
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     # To debug: print("Debug messages...", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     print(dest[i][0], dest[i][1]) # output a destination point to be reached by one of your drones. The first line corresponds to the first of your drones that you were provided as input, the next to the second, etc.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
